name: Cargo.toml format check (taplo)
on:
  pull_request:
    paths:
      - '**/Cargo.toml'

jobs:
  cargo_toml_format:
    name: Cargo.toml format check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Taplo
        uses: uncenter/setup-taplo@v1.0.8

      - name: Taplo format check
        run: taplo fmt --check
